name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "bossa-jpg"
          reponame: "rick-and-morty-app"
          token: ${{ secrets.GITHUB_TOKEN }}
